# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: admob_inline_ads_in_flutter
description: A sample app demonstrates the usage of the banner and native inline ads.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # COMPLETE: Add google_mobile_ads as a dependency
  google_mobile_ads: ^0.13.0
  flutter_gallery_assets: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - packages/flutter_gallery_assets/crane/destinations/fly_0.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_1.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_2.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_3.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_4.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_5.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_6.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_7.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_8.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_9.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_10.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_11.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_12.jpg
    - packages/flutter_gallery_assets/crane/destinations/fly_13.jpg
